[package]
name = "bug"
version = "0.1.0"
edition = "2024"

[dependencies]
batbox-la.workspace = true
winit.workspace = true
gl.workspace = true
ugli.workspace = true
glutin.workspace = true
glutin-winit.workspace = true
raw-window-handle.workspace = true
